#!/usr/bin/env python3
"""
Generate gateway + ESP-NOW node alona_config.h files from one JSON manifest.

Usage (from alona-os-firmware repo root):
  cp property.local.json.example property.local.json
  # edit property.local.json — wifi, mqtt, espnow.channel + gateway_sta_mac, etc.
  python3 scripts/sync_property_manifest.py

Options:
  --manifest PATH   default: ./property.local.json (next to this script's repo root)
  --dry-run         print paths only, do not write files
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def firmware_root() -> Path:
    return Path(__file__).resolve().parent.parent


def c_string_literal(s: str) -> str:
    escaped = (
        s.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )
    return f'"{escaped}"'


def parse_mac(mac_str: str) -> list[int]:
    cleaned = mac_str.strip().replace("-", ":")
    parts = [p for p in cleaned.split(":") if p != ""]
    if len(parts) != 6:
        raise ValueError(f'gateway_sta_mac must have 6 octets, got {mac_str!r}')
    out = []
    for p in parts:
        out.append(int(p, 16))
    return out


def load_manifest(path: Path) -> dict:
    with path.open(encoding="utf-8") as f:
        return json.load(f)


def require(obj: dict, *keys: str):
    cur = obj
    for k in keys:
        if k not in cur or cur[k] is None:
            raise KeyError(".".join(keys))
        cur = cur[k]
    return cur


def gateway_header(data: dict) -> str:
    wifi = require(data, "wifi")
    mqtt = require(data, "mqtt")
    gw = data.get("gateway") or {}

    ssid = wifi["ssid"]
    password = wifi["password"]
    host = mqtt["host"]
    port = int(mqtt["port"])
    topic = mqtt["living_room_topic"]

    label = gw.get("device_id_label", "living-room-gateway")
    dedupe = int(gw.get("dedupe_window_ms", 2000))
    qdepth = int(gw.get("espnow_rx_queue_depth", 12))

    lines = [
        "/**",
        " * generated by scripts/sync_property_manifest.py — do not edit by hand",
        " */",
        "#pragma once",
        "",
        f"#define ALONA_WIFI_SSID {c_string_literal(str(ssid))}",
        f"#define ALONA_WIFI_PASSWORD {c_string_literal(str(password))}",
        "",
        f"#define ALONA_MQTT_HOST {c_string_literal(str(host))}",
        f"#define ALONA_MQTT_PORT {port}",
        f"#define ALONA_MQTT_TOPIC {c_string_literal(str(topic))}",
        "",
        f"#define ALONA_GATEWAY_DEVICE_ID {c_string_literal(str(label))}",
        "",
        f"#define ALONA_DEDUPE_WINDOW_MS {dedupe}",
        "",
        f"#define ALONA_ESPNOW_RX_QUEUE_DEPTH {qdepth}",
        "",
    ]
    return "\n".join(lines)


def temp_humidity_header(data: dict) -> str:
    espnow = require(data, "espnow")
    nodes = require(data, "nodes")
    th = nodes["temp_humidity"]

    channel = int(espnow["wifi_channel"])
    mac = parse_mac(str(espnow["gateway_sta_mac"]))
    device_id = str(th["device_id"])
    interval = int(th["send_interval_ms"])

    mac_lines = "\n".join(
        f"#define ALONA_GATEWAY_PEER_MAC_B{i} 0x{b:02x}" for i, b in enumerate(mac)
    )

    lines = [
        "/**",
        " * generated by scripts/sync_property_manifest.py — do not edit by hand",
        " * ESP32-C3 Mini-1: idf.py set-target esp32c3",
        " */",
        "#pragma once",
        "",
        f"#define ALONA_WIFI_CHANNEL {channel}",
        "",
        f"#define ALONA_DEVICE_ID {c_string_literal(device_id)}",
        "",
        f"#define ALONA_ESPNOW_SEND_INTERVAL_MS {interval}",
        "",
        "/** gateway STA MAC bytes (from gateway serial: \"gateway sta mac\") */",
        mac_lines,
        "",
    ]
    return "\n".join(lines)


def fake_node_header(data: dict) -> str:
    espnow = require(data, "espnow")
    nodes = require(data, "nodes")
    fb = nodes["fake_bench"]

    channel = int(espnow["wifi_channel"])
    mac = parse_mac(str(espnow["gateway_sta_mac"]))
    device_id = str(fb["device_id"])
    interval = int(fb["send_interval_ms"])

    mac_lines = "\n".join(
        f"#define ALONA_GATEWAY_PEER_MAC_B{i} 0x{b:02x}" for i, b in enumerate(mac)
    )

    lines = [
        "/**",
        " * generated by scripts/sync_property_manifest.py — do not edit by hand",
        " */",
        "#pragma once",
        "",
        f"#define ALONA_WIFI_CHANNEL {channel}",
        "",
        f"#define ALONA_DEFAULT_DEVICE_ID {c_string_literal(device_id)}",
        "",
        f"#define ALONA_ESPNOW_SEND_INTERVAL_MS {interval}",
        "",
        "/** gateway STA MAC bytes (from gateway serial: \"gateway sta mac\") */",
        mac_lines,
        "",
    ]
    return "\n".join(lines)


def print_env_snippet(data: dict) -> None:
    mqtt = require(data, "mqtt")
    host = mqtt["host"]
    port = int(mqtt["port"])
    topic = mqtt["living_room_topic"]
    print("\n# Paste into Pi / shell env for alona-os-core (broker reachable from Pi)", file=sys.stderr)
    print("# Matches gateway manifest MQTT settings.", file=sys.stderr)
    print(f"export ALONA_MQTT_HOST={host}", file=sys.stderr)
    print(f"export ALONA_MQTT_PORT={port}", file=sys.stderr)
    print(f"export ALONA_MQTT_TOPICS={topic}", file=sys.stderr)


def main() -> int:
    root = firmware_root()
    ap = argparse.ArgumentParser(description="Generate alona_config.h files from property.local.json")
    ap.add_argument(
        "--manifest",
        type=Path,
        default=root / "property.local.json",
        help="path to JSON manifest (default: ./property.local.json under firmware root)",
    )
    ap.add_argument("--dry-run", action="store_true", help="do not write files")
    args = ap.parse_args()
    manifest_path = args.manifest.expanduser().resolve()
    if not manifest_path.is_file():
        print(f"error: manifest not found: {manifest_path}", file=sys.stderr)
        print(f"copy {root / 'property.local.json.example'} and edit.", file=sys.stderr)
        return 1

    try:
        data = load_manifest(manifest_path)
    except json.JSONDecodeError as e:
        print(f"error: invalid JSON: {e}", file=sys.stderr)
        return 1

    outs = [
        (root / "gateway/main/alona_config.h", gateway_header(data)),
        (root / "examples/temp_humidity_node/main/alona_config.h", temp_humidity_header(data)),
        (root / "examples/espnow_fake_node/main/alona_config.h", fake_node_header(data)),
    ]

    espnow = data.get("espnow") or {}
    try:
        mac_vals = parse_mac(str(espnow.get("gateway_sta_mac", "00:00:00:00:00:00")))
        if all(b == 0 for b in mac_vals):
            print(
                "warning: gateway_sta_mac is all zeros — set it from gateway serial "
                '("gateway sta mac …") before relying on ESP-NOW nodes.',
                file=sys.stderr,
            )
    except ValueError as e:
        print(f"warning: invalid gateway_sta_mac: {e}", file=sys.stderr)

    print_env_snippet(data)

    for path, content in outs:
        if args.dry_run:
            print(f"would write {path}")
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path}", file=sys.stderr)

    print("done.", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
